[tool.poetry]
name = "prog"
version = "0.0.0"
description = "My Prog"
authors = ["Frederic Lepied <flepied@redhat.com>"]

[tool.poetry.dependencies]  # main dependency group
python = ">=3.8.1,<3.12"

lib = "*"
